@startuml
queue LockFreeQueue

BinStreamApp -> AggTradeStreamServer: start
loop while context is here
    alt Quote is available
        AggTradeStreamServer -> LockFreeQueue: request Quote from queue
        AggTradeStreamServer <-- LockFreeQueue: pop Quote
        AggTradeStreamServer -> AggTradeStreamServer: take last N messages\n and add them to batch
        note right: N value should be configured.
        AggTradeStreamServer -> AggTradeStreamServer: write stream to client
    end
end

BinStreamApp -> AggTradeStreamServer: stop
AggTradeStreamServer -> AggTradeStreamServer: shutdown server
AggTradeStreamServer -> AggTradeStreamServer: clean resources

@enduml