@startuml
!include_once common_classes.puml

hide empty members
class BinStreamApp
{
    +start(): bool
}

class ConfigServiceBuilder<T>
{
    +build(): T
}

ConfigServiceBuilder ..> LoggerConfigService : <<create>>
BinStreamApp ..> ConfigServiceBuilder : <<use>>
@enduml