[Common]
DaemonFifoSize=65536
ControlSocketPath=/tmp/dlt-ctrl.sock
DltPipeDir=/tmp/dlt
ProtocolVersion=2

[OfflineStorage]
OfflineLoggingMode=1
OfflineLogStoragePath=/tmp/
OfflineLogStorageMaxDevices=1
OfflineLogStorageMaxSize=200M

[TargetCommunication]
DltLocalIpAddress=127.0.0.1
DltTcpPort=3490
