[Common]
DaemonFifoSize=65536
ControlSocketPath=/tmp/dlt-ctrl.sock
DltPipeDir=/tmp/dlt

[OfflineStorage]
OfflineLogStoragePath=/tmp/
OfflineLoggingMode=1
OfflineLogStorageMaxDevices=1
OfflineLogStorageMaxSize=200M

[TargetCommunication]
DltLocalIpAddress=127.0.0.1
DltTcpPort=3490