name: Common checks(linter, formatter, tests, coverage)

permissions:
  contents: write
  pull-requests: write
  checks: write

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "**" ] 

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake lcov libgtest-dev g++-13 libc6 wget lsb-release software-properties-common gnupg

      - name: Run Build and Tests
        env:
          CC: gcc-13
          CXX: g++-13
        run: |
          chmod +x ${{ github.workspace }}/tools/build_and_run_tests.sh
          ${{ github.workspace }}/tools/build_and_run_tests.sh -c -cl

      - name: Publish Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "${{ github.workspace }}/coverage_report/TEST_*.xml"
          comment_mode: always


      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ${{ github.workspace }}/coverage_report/final_coverage.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
          annotate_notice: true

      - name: Run C/C++ linter action
        uses: cpp-linter/cpp-linter-action@v2.18.0
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          no-lgtm: true
          file-annotations: true
          extra-args: '-header-filter=src/.* -Wno-unknown-warning-option -std=c++20 -Wall'
          style: "file"
          database: '${{ github.workspace }}/build'
          tidy-checks: ""
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
          step-summary: true
          tidy-review: true
          format-review: true
          passive-reviews: true
          version: 18
      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
        

