name: Linter check (clang-tidy, clang-format).

permissions:
  contents: write
  pull-requests: write
  checks: write

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "**" ]

jobs:
  linter:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure CMake (Generate compile_commands.json)
        run: |
          cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      
      - name: Run C/C++ linter action
        uses: cpp-linter/cpp-linter-action@v2.18.0
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          no-lgtm: true
          file-annotations: true
          extra-args: '-header-filter=src/.* -Wno-unknown-warning-option -std=c++20 -Wall'
          style: "file"
          database: '${{ github.workspace }}/build'
          tidy-checks: ""
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
          step-summary: true
          tidy-review: true
          format-review: true
          passive-reviews: true
          version: 18
      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1